//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesenvolvimentoWEB.Vendas.ServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CartaoContract", Namespace="http://schemas.datacontract.org/2004/07/Projeto02_WCFPagamentos.Models")]
    [System.SerializableAttribute()]
    public partial class CartaoContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LimiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCartaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Limite {
            get {
                return this.LimiteField;
            }
            set {
                if ((this.LimiteField.Equals(value) != true)) {
                    this.LimiteField = value;
                    this.RaisePropertyChanged("Limite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCartao {
            get {
                return this.NumeroCartaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCartaoField, value) != true)) {
                    this.NumeroCartaoField = value;
                    this.RaisePropertyChanged("NumeroCartao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagamentoContract", Namespace="http://schemas.datacontract.org/2004/07/Projeto02_WCFPagamentos.Models")]
    [System.SerializableAttribute()]
    public partial class PagamentoContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ValorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroCartao {
            get {
                return this.NumeroCartaoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroCartaoField, value) != true)) {
                    this.NumeroCartaoField = value;
                    this.RaisePropertyChanged("NumeroCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroPedido {
            get {
                return this.NumeroPedidoField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroPedidoField, value) != true)) {
                    this.NumeroPedidoField = value;
                    this.RaisePropertyChanged("NumeroPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Valor {
            get {
                return this.ValorField;
            }
            set {
                if ((this.ValorField.Equals(value) != true)) {
                    this.ValorField = value;
                    this.RaisePropertyChanged("Valor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProxy.IServicePagamentos")]
    public interface IServicePagamentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePagamentos/ListarCartoes", ReplyAction="http://tempuri.org/IServicePagamentos/ListarCartoesResponse")]
        DesenvolvimentoWEB.Vendas.ServiceProxy.CartaoContract[] ListarCartoes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePagamentos/ListarCartoes", ReplyAction="http://tempuri.org/IServicePagamentos/ListarCartoesResponse")]
        System.Threading.Tasks.Task<DesenvolvimentoWEB.Vendas.ServiceProxy.CartaoContract[]> ListarCartoesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePagamentos/EfetuarPagamento", ReplyAction="http://tempuri.org/IServicePagamentos/EfetuarPagamentoResponse")]
        int EfetuarPagamento(DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePagamentos/EfetuarPagamento", ReplyAction="http://tempuri.org/IServicePagamentos/EfetuarPagamentoResponse")]
        System.Threading.Tasks.Task<int> EfetuarPagamentoAsync(DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract pagamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePagamentos/ListarPagamentos", ReplyAction="http://tempuri.org/IServicePagamentos/ListarPagamentosResponse")]
        DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract[] ListarPagamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicePagamentos/ListarPagamentos", ReplyAction="http://tempuri.org/IServicePagamentos/ListarPagamentosResponse")]
        System.Threading.Tasks.Task<DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract[]> ListarPagamentosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicePagamentosChannel : DesenvolvimentoWEB.Vendas.ServiceProxy.IServicePagamentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicePagamentosClient : System.ServiceModel.ClientBase<DesenvolvimentoWEB.Vendas.ServiceProxy.IServicePagamentos>, DesenvolvimentoWEB.Vendas.ServiceProxy.IServicePagamentos {
        
        public ServicePagamentosClient() {
        }
        
        public ServicePagamentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicePagamentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePagamentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicePagamentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DesenvolvimentoWEB.Vendas.ServiceProxy.CartaoContract[] ListarCartoes() {
            return base.Channel.ListarCartoes();
        }
        
        public System.Threading.Tasks.Task<DesenvolvimentoWEB.Vendas.ServiceProxy.CartaoContract[]> ListarCartoesAsync() {
            return base.Channel.ListarCartoesAsync();
        }
        
        public int EfetuarPagamento(DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract pagamento) {
            return base.Channel.EfetuarPagamento(pagamento);
        }
        
        public System.Threading.Tasks.Task<int> EfetuarPagamentoAsync(DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract pagamento) {
            return base.Channel.EfetuarPagamentoAsync(pagamento);
        }
        
        public DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract[] ListarPagamentos() {
            return base.Channel.ListarPagamentos();
        }
        
        public System.Threading.Tasks.Task<DesenvolvimentoWEB.Vendas.ServiceProxy.PagamentoContract[]> ListarPagamentosAsync() {
            return base.Channel.ListarPagamentosAsync();
        }
    }
}
