//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoWeb_CadastroEventos.Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convidado
    {
        public string CPF { get; set; }
        public int IdEvento { get; set; }
        public string Nome { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
    
        public virtual Evento EventoInfo { get; set; }
    }
}
